security:
  oauth2:
    client:
      client-id: MemberSystem2
      client-secret: 123456
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token

server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/