server:
  port: 8081
  servlet:
    context-path: /orderSystem
security:
  oauth2:
    client:
      client-id: OrderSystem
      client-secret: 12345
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/