spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 1

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml

logging:
  config: classpath:logback.xml
  level:
    com:
      sym:
        oauth2ssoserver: debug

